/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conexao.ConectaBD;
import Conexao.ConexaoException;
import Conexao.DaoException;
import Control.DaoLogin;
import Model.ClassLogin;
import Model.DadosInvalidoException;
import Model.ModelTable;
import Model.SenhaInvalidaException;
import Model.UsuarioInvalidoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author patricia
 */
public class CadastroLogin extends javax.swing.JFrame {

    ClassLogin login = new ClassLogin();
    DaoLogin daoL = new DaoLogin();
    ConectaBD con = new ConectaBD();
    ClassLogin model_Login = new ClassLogin();
    /**
     * Creates new form Equipamentos
     */
    public CadastroLogin() throws ConexaoException, SQLException {
        initComponents();
        
        jTextField1Id_Login.setEnabled(false);
               
        preecherTabela("select * from login order by id_login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1Alterar_Func = new javax.swing.JButton();
        jButton2Voltar_Func = new javax.swing.JButton();
        jButton4_Pesquisar_Func = new javax.swing.JButton();
        jScrollPane2Tabela = new javax.swing.JScrollPane();
        jTable1Pesquisa_usuario = new javax.swing.JTable();
        jButton1excluir_Func = new javax.swing.JButton();
        jButton1Cadastrar_Func = new javax.swing.JButton();
        jTextField1Usuario = new javax.swing.JTextField();
        jPasswordField1Senha = new javax.swing.JPasswordField();
        jTextField1Id_Login = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE USUARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, -1));

        jTextField2nome.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2nomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Senha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Login");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jButton1Alterar_Func.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1Alterar_Func.setText("Alterar");
        jButton1Alterar_Func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1Alterar_FuncActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Alterar_Func, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 100, 30));

        jButton2Voltar_Func.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2Voltar_Func.setText("Voltar");
        jButton2Voltar_Func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2Voltar_FuncActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2Voltar_Func, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 100, 30));

        jButton4_Pesquisar_Func.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4_Pesquisar_Func.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/pesquisar.png"))); // NOI18N
        jButton4_Pesquisar_Func.setBorderPainted(false);
        jButton4_Pesquisar_Func.setContentAreaFilled(false);
        jButton4_Pesquisar_Func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_Pesquisar_FuncActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4_Pesquisar_Func, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 40, 50));

        jScrollPane2Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2TabelaMouseClicked(evt);
            }
        });

        jTable1Pesquisa_usuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1Pesquisa_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1Pesquisa_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1Pesquisa_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1Pesquisa_usuarioMouseClicked(evt);
            }
        });
        jScrollPane2Tabela.setViewportView(jTable1Pesquisa_usuario);

        getContentPane().add(jScrollPane2Tabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 400, 110));

        jButton1excluir_Func.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1excluir_Func.setText("Excluir");
        jButton1excluir_Func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1excluir_FuncActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1excluir_Func, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 100, 30));

        jButton1Cadastrar_Func.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1Cadastrar_Func.setText("Cadastrar");
        jButton1Cadastrar_Func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1Cadastrar_FuncActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Cadastrar_Func, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 110, 30));

        jTextField1Usuario.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1Usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField1Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 30));

        jPasswordField1Senha.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1Senha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jPasswordField1Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 260, 30));

        jTextField1Id_Login.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField1Id_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 30));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/BackgroundtE.jpg"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(619, 460));
        jLabel8.setMinimumSize(new java.awt.Dimension(619, 460));
        jLabel8.setPreferredSize(new java.awt.Dimension(619, 460));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 510));

        setSize(new java.awt.Dimension(853, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2nomeActionPerformed

    private void jButton1Alterar_FuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1Alterar_FuncActionPerformed
        //Codigo Alterar Usuario
      if(this.jPasswordField1Senha.getText().equals("")){      
        JOptionPane.showMessageDialog(null, "Campo Senha está vazio, coloque uma Senha!");
      }else{  
        try {
            
            login.setUsuario(jTextField1Usuario.getText());
            login.setSenha(jPasswordField1Senha.getText());
            login.setNome(jTextField2nome.getText());
            login.setId_Login(Integer.parseInt(jTextField1Id_Login.getText()));
            daoL.Alterar(login);
        JOptionPane.showMessageDialog(null, "Dados alterado com sucesso");
        
        } catch (DadosInvalidoException ex) {
            JOptionPane.showMessageDialog(null, "Dados Invalidos");
        } catch (ConexaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        limpar();
                
        try {
            preecherTabela("select * from login order by id_login");
        } catch (ConexaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton1Alterar_FuncActionPerformed

    private void jButton4_Pesquisar_FuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_Pesquisar_FuncActionPerformed
        // Fazer uma consulta no banco dados
        try {
            login.setNome(jTextField2nome.getText());
            
            daoL.Pesquisar(login);
            
        } catch (ConexaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UsuarioInvalidoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SenhaInvalidaException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DadosInvalidoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
            jTextField1Usuario.setText(model_Login.getUsuario());
            jPasswordField1Senha.setText(model_Login.getSenha());
            
        try {
            preecherTabela("select * from login where nome like'%"+jTextField2nome.getText()+"%'");
        } catch (ConexaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4_Pesquisar_FuncActionPerformed
 
    private void jButton1excluir_FuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1excluir_FuncActionPerformed
        
         //Confirmação de Exclusão
            int confirmar = JOptionPane.showConfirmDialog(null, "Deseja Realmente Excluir o Usuario "+"-"+jTextField1Id_Login.getText()+" "+jTextField2nome.getText(),"ATENÇÂO", JOptionPane.YES_NO_OPTION );
            
            if(confirmar == JOptionPane.YES_OPTION){
        
                try {
                    login.setId_Login(Integer.parseInt(jTextField1Id_Login.getText()));
                // Codigo Excluir Usuario
                    daoL.Excluir(login);
                
                    //Informando que o produto foi exclído com sucesso
                JOptionPane.showMessageDialog(null, "Usuario "+jTextField1Usuario.getText()+"-"+" excluído com sucesso!");
                limpar();
                } catch (DadosInvalidoException ex) {
                    Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ConexaoException ex) {
                    Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DaoException ex) {
                    Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        try {
            preecherTabela("select * from login order by id_login");
        } catch (ConexaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_jButton1excluir_FuncActionPerformed

    private void jButton1Cadastrar_FuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1Cadastrar_FuncActionPerformed
         if(this.jPasswordField1Senha.getText().equals("")){      
        JOptionPane.showMessageDialog(null, "Campo Senha está vazio, coloque uma Senha!");
      }else{  
        
        try {
            //Codigo Cadastrar Usuario
            
            login.setNome(jTextField2nome.getText().trim());
            login.setUsuario(jTextField1Usuario.getText().trim());
            login.setSenha(jPasswordField1Senha.getText().trim());
        
        daoL.Cadastrar(login);
            
            JOptionPane.showMessageDialog(null, "Dados Cadastrado com sucesso");
            
        } catch (DadosInvalidoException ex) {
           JOptionPane.showMessageDialog(null, "Dados Invalido");
           
        } catch (ConexaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            preecherTabela("select * from login order by id_login");
        } catch (ConexaoException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpar();
         }
    }//GEN-LAST:event_jButton1Cadastrar_FuncActionPerformed

    private void jButton2Voltar_FuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2Voltar_FuncActionPerformed
        //Voltar para tela Inicial
        dispose();
    }//GEN-LAST:event_jButton2Voltar_FuncActionPerformed

    private void jScrollPane2TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2TabelaMouseClicked

    }//GEN-LAST:event_jScrollPane2TabelaMouseClicked

    private void jTable1Pesquisa_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1Pesquisa_usuarioMouseClicked
       //Codigo para preencher Campos
         String id_Login = "" + jTable1Pesquisa_usuario.getValueAt(jTable1Pesquisa_usuario.getSelectedRow(), 0);
        jTextField1Id_Login.setText(id_Login);
        String nome = "" + jTable1Pesquisa_usuario.getValueAt(jTable1Pesquisa_usuario.getSelectedRow(), 1);
        jTextField2nome.setText(nome);
        String usuario = "" + jTable1Pesquisa_usuario.getValueAt(jTable1Pesquisa_usuario.getSelectedRow(), 2);
        jTextField1Usuario.setText(usuario);
         
    }//GEN-LAST:event_jTable1Pesquisa_usuarioMouseClicked
public void preecherTabela(String Sql) throws ConexaoException, SQLException{
   // Metodo preencher tabela com dados do banco
    ArrayList dados = new ArrayList();
    String [] colunas = new String[] {"COD","NOME","LOGIN"};
    con.conectar();
    con.executaSql(Sql);
       try{
            con.rs.first();
            do{   
            dados.add(new Object[]{con.rs.getString("id_login"),con.rs.getString("nome"),con.rs.getString("usuario")});
               }while(con.rs.next());
            
       }catch (SQLException ex){
           JOptionPane.showMessageDialog(null, " Erro ao peencher o ArreyList!\nERRO"+ ex);
       } 
       
       DefaultTableCellRenderer rendererCentro = new DefaultTableCellRenderer();
       rendererCentro.setHorizontalAlignment(SwingConstants.CENTER);
       DefaultTableCellRenderer rendererDireita = new DefaultTableCellRenderer();
       rendererCentro.setHorizontalAlignment(SwingConstants.RIGHT);
       DefaultTableCellRenderer rendererEsquerda = new DefaultTableCellRenderer();
       rendererCentro.setHorizontalAlignment(SwingConstants.LEFT);
       ModelTable modelo = new ModelTable(dados, colunas);
       jTable1Pesquisa_usuario.setModel(modelo);
       jTable1Pesquisa_usuario.getColumnModel().getColumn(0).setMaxWidth(80);
       jTable1Pesquisa_usuario.getColumnModel().getColumn(1).setMaxWidth(320);
       jTable1Pesquisa_usuario.getColumnModel().getColumn(2).setMaxWidth(150);
       jTable1Pesquisa_usuario.getTableHeader().setReorderingAllowed(false);
       jTable1Pesquisa_usuario.setAutoResizeMode(jTable1Pesquisa_usuario.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
       jTable1Pesquisa_usuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       con.desconectar();
}

public void limpar(){
    //Metodo para Limpar Campos
        jTextField1Id_Login.setText("");
        jTextField2nome.setText("");
        jTextField1Usuario.setText("");
        jPasswordField1Senha.setText("");
        
}
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroLogin().setVisible(true);
                } catch (ConexaoException ex) {
                    Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Alterar_Func;
    private javax.swing.JButton jButton1Cadastrar_Func;
    private javax.swing.JButton jButton1excluir_Func;
    private javax.swing.JButton jButton2Voltar_Func;
    private javax.swing.JButton jButton4_Pesquisar_Func;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1Senha;
    private javax.swing.JScrollPane jScrollPane2Tabela;
    private javax.swing.JTable jTable1Pesquisa_usuario;
    private javax.swing.JTextField jTextField1Id_Login;
    private javax.swing.JTextField jTextField1Usuario;
    private javax.swing.JTextField jTextField2nome;
    // End of variables declaration//GEN-END:variables
}
