/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conexao.ConectaBD;
import Conexao.ConexaoException;
import Conexao.DaoException;
import Control.DaoClientes;
import Model.Cliente;
import Model.DadosInvalidoException;
import Model.DataInvalidaException;
import Model.ModelTable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author patricia
 */
public class DadosCliente extends javax.swing.JFrame {
ConectaBD con = new ConectaBD();
TelaCadCliente cl = new TelaCadCliente();
Cliente cc = new Cliente();
DaoClientes dc = new DaoClientes();
Cliente model_cl = new Cliente();
    /**
     * Creates new form DadosCliente
     */
    public DadosCliente() throws ConexaoException, SQLException {
        initComponents();
        con.conectar();
        
        preecherDadosCliente("select * from cliente order by codCliente");
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Cliente = new javax.swing.JTable();
        jTextField5Pesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1Nome = new javax.swing.JRadioButton();
        jRadioButton2CpfCnpj = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jTable1Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1ClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Cliente);

        jTextField5Pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5PesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5PesquisarKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Dados de Clientes");

        buttonGroup1.add(jRadioButton1Nome);
        jRadioButton1Nome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton1Nome.setSelected(true);
        jRadioButton1Nome.setText("Nome");

        buttonGroup1.add(jRadioButton2CpfCnpj);
        jRadioButton2CpfCnpj.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton2CpfCnpj.setText("Cpf\\Cnpj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField5Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2CpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(707, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jRadioButton1Nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2CpfCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1341, 671));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1ClienteMouseClicked
        int index = jTable1Cliente.getSelectedRow();
       
        String codCliente = jTable1Cliente.getValueAt(index, 0).toString();
         String nome = jTable1Cliente.getValueAt(index, 1).toString();
          String cpf_Cnpj = jTable1Cliente.getValueAt(index, 2).toString();
           String logradouro = jTable1Cliente.getValueAt(index, 3).toString();
            String numero = jTable1Cliente.getValueAt(index, 4).toString();
             String complemento = jTable1Cliente.getValueAt(index, 5).toString();
              String bairro = jTable1Cliente.getValueAt(index, 6).toString();
               String cep = jTable1Cliente.getValueAt(index, 7).toString();
                String municipio = jTable1Cliente.getValueAt(index, 8).toString();
                String uf = jTable1Cliente.getValueAt(index, 9).toString();
                String fone1 = jTable1Cliente.getValueAt(index, 10).toString();
              String fone2 = jTable1Cliente.getValueAt(index, 11).toString();
             String email = jTable1Cliente.getValueAt(index, 12).toString();
            String dataCadastro = jTable1Cliente.getValueAt(index, 13).toString();
           String observacao = jTable1Cliente.getValueAt(index, 14).toString();
                
           cl.setVisible(true);
           cl.pack();
           cl.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                 
                 cl.jTextField2CodCliente.setText(codCliente);
                 cl.jTextField3Nome.setText(nome);
                 cl.jTextField6Cpf.setText(cpf_Cnpj);
                 cl.jTextField4Logradouro.setText(logradouro);
                 cl.jTextField5Numero.setText(numero);
                 cl.jTextField7Complemento.setText(complemento);
                 cl.jTextField13Bairro.setText(bairro);
                 cl.jFormattedTextField1Cep.setText(cep);
                 cl.jTextField14Cidade.setText(municipio);
                 cl.jTextField1Uf.setText(uf);
                 cl.jFormattedTextField1Fone1.setText(fone1);
                 cl.jFormattedTextField2Fone2.setText(fone2);
                 cl.jTextField8Email.setText(email);
                 cl.jFormattedTextField1DataCadastro.setText(dataCadastro);
                 cl.jObservacao.setText(observacao);
                 
        dispose();   
    }//GEN-LAST:event_jTable1ClienteMouseClicked

    private void jTextField5PesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5PesquisarKeyReleased
    
               // Fazer uma pesquisar no banco dados 
        
       if(jRadioButton1Nome.isSelected()){
             
                try {

                    preecherDadosCliente("select * from cliente where nome " + "like'%"+jTextField5Pesquisar.getText()+"%'");
             
                } catch (ConexaoException ex) {
                 Logger.getLogger(TelaCadCliente.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(TelaCadCliente.class.getName()).log(Level.SEVERE, null, ex);
             }
      }else{
   
             try {
                 preecherDadosCliente("select * from cliente where cpf_Cnpj " + "like'%"+jTextField5Pesquisar.getText()+"%'");
             } catch (ConexaoException ex) {
                 Logger.getLogger(TelaCadCliente.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(TelaCadCliente.class.getName()).log(Level.SEVERE, null, ex);
             }
       }    
    }//GEN-LAST:event_jTextField5PesquisarKeyReleased

    private void jTextField5PesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5PesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5PesquisarKeyPressed

    /**
     * @param args the command line arguments
     */
    
     public void preecherDadosCliente(String Sql) throws ConexaoException, SQLException{
    ArrayList dados = new ArrayList();
    String [] colunas = new String[] {"COD","NOME","CPF-CNPJ","LOGRADOURO","NUM","COMPLEMENTO","BAIRRO","CEP","MUNICIPIO","UF","FONE 1","FONE 2","EMAIL","DATA CADASTRO","OBSERVAÇÃO"};
    con.conectar();
    con.executaSql(Sql);
                    
           con.rs.first();
               do{
                     dados.add(new Object[]{con.rs.getString("codCliente"),con.rs.getString("nome"),con.rs.getString("cpf_Cnpj")
                     ,con.rs.getString("logradouro"),con.rs.getString("numero"),con.rs.getString("complemento"),con.rs.getString("bairro")
                     ,con.rs.getString("cep"),con.rs.getString("municipio"),con.rs.getString("uf"),con.rs.getString("fone1"),con.rs.getString("fone2")
                     ,con.rs.getString("email"),con.rs.getString("dataCadastro"),con.rs.getString("observacao")});
                                  
     }while(con.rs.next());                  
      
           //JOptionPane.showMessageDialog(null, "DADOS NÃO ENCONTRADO"); 
       
       DefaultTableCellRenderer rendererCentro = new DefaultTableCellRenderer();
       rendererCentro.setHorizontalAlignment(SwingConstants.CENTER);
       DefaultTableCellRenderer rendererDireita = new DefaultTableCellRenderer();
       rendererCentro.setHorizontalAlignment(SwingConstants.RIGHT);
       DefaultTableCellRenderer rendererEsquerda = new DefaultTableCellRenderer();
       rendererCentro.setHorizontalAlignment(SwingConstants.LEFT);
       ModelTable modelo = new ModelTable(dados, colunas);
       jTable1Cliente.setModel(modelo);
       jTable1Cliente.getColumnModel().getColumn(0).setMaxWidth(50);
       jTable1Cliente.getColumnModel().getColumn(1).setMaxWidth(200);
       jTable1Cliente.getColumnModel().getColumn(2).setMaxWidth(150);
       jTable1Cliente.getColumnModel().getColumn(3).setMaxWidth(200);
       jTable1Cliente.getColumnModel().getColumn(4).setMaxWidth(60);
       jTable1Cliente.getColumnModel().getColumn(5).setMaxWidth(200);
       jTable1Cliente.getColumnModel().getColumn(6).setMaxWidth(80);
       jTable1Cliente.getColumnModel().getColumn(7).setMaxWidth(70);
       jTable1Cliente.getColumnModel().getColumn(8).setMaxWidth(90);
       jTable1Cliente.getColumnModel().getColumn(9).setMaxWidth(40);
       jTable1Cliente.getColumnModel().getColumn(10).setMaxWidth(90);
       jTable1Cliente.getColumnModel().getColumn(11).setMaxWidth(90);
       jTable1Cliente.getColumnModel().getColumn(12).setMaxWidth(150);
       jTable1Cliente.getColumnModel().getColumn(13).setMaxWidth(80);
       jTable1Cliente.getColumnModel().getColumn(14).setMaxWidth(100);
       jTable1Cliente.getTableHeader().setReorderingAllowed(false);
       jTable1Cliente.setAutoResizeMode(jTable1Cliente.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
       jTable1Cliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       con.desconectar();
}
                
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DadosCliente().setVisible(true);
                } catch (ConexaoException ex) {
                    Logger.getLogger(DadosCliente.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(DadosCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1Nome;
    private javax.swing.JRadioButton jRadioButton2CpfCnpj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Cliente;
    private javax.swing.JTextField jTextField5Pesquisar;
    // End of variables declaration//GEN-END:variables
}
