/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Conexao.ConectaBD;
import Conexao.ConexaoException;
import Conexao.IGerenciadorConexao;
import Control.DaoLogin;
import Model.ClassLogin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author patricia
 */
public class Login extends javax.swing.JFrame {
    
    ClassLogin login = new ClassLogin();
    DaoLogin daoL = new DaoLogin();
    ConectaBD con = new ConectaBD();
    ClassLogin model = new ClassLogin();
    ResultSet rs = null;
    private final IGerenciadorConexao g;
    /**
     * Creates new form Equipamentos
     */
    public Login() {
        initComponents();
        g =  ConectaBD.getInstancia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1_Entra = new javax.swing.JButton();
        jButton2_voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Login = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2Senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1_Entra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1_Entra.setText("Entrar");
        jButton1_Entra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_EntraActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Entra, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 90, 30));

        jButton2_voltar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2_voltar.setText("Sair");
        jButton2_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 80, 20));

        jTextField_Login.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 330, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 90, 20));

        jPasswordField2Senha.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField2Senha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jPasswordField2Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 330, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/BravaTintas.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1140, 550));

        setSize(new java.awt.Dimension(1122, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LoginActionPerformed

    private void jButton1_EntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_EntraActionPerformed
         boolean resposta = false;
        try {
            resposta = consultar(jTextField_Login.getText().toString(), jPasswordField2Senha.getText()); //Pego usuario e senha digitados e jogo no metodo consultar para validar
        } catch (ConexaoException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (resposta == true) {//Se Usuario e senha estiverem corretos
            TelaPrincipal principal = new TelaPrincipal();
             
            principal.setVisible(true);
        dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário e(ou) senha incorretos!\nEntre em contato com um Administrador do Sistema");
        jTextField_Login.setText("");
        jPasswordField2Senha.setText("");
        }
        getRootPane().setDefaultButton(jButton1_Entra);
    }//GEN-LAST:event_jButton1_EntraActionPerformed

    private void jButton2_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_voltarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2_voltarActionPerformed
public boolean consultar(String usuario, String senha) throws ConexaoException {
        boolean autenticado = false;
        String sql = "SELECT usuario, senha FROM login WHERE usuario=? and senha=?";
        Connection c = g.conectar();
        try {
            
            PreparedStatement pstm = c.prepareStatement(sql);
            pstm.setString(1, usuario);
            pstm.setString(2, senha);
            ResultSet rs;
            rs = pstm.executeQuery();
            if (rs.next()) {
                String user = rs.getString("usuario");
                String pass = rs.getString("senha");
                autenticado = true;
            } else {
                //JOptionPane.showMessageDialog(this, "Acesso Negado \nInforme o setor de Inventário");
                pstm.close();
                return autenticado;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return autenticado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Entra;
    private javax.swing.JButton jButton2_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField2Senha;
    private javax.swing.JTextField jTextField_Login;
    // End of variables declaration//GEN-END:variables
}
