package View;

import Conexao.ConexaoException;
import Model.data;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Victor
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    data mostra_data; 
    String seta_look="javax.swing.plaf.metal.MetalLookAndFeel";
    
    public TelaPrincipal() {
        initComponents();
        
        mostra_data = new data();
        mostra_data.le_data();
        label_data.setText(mostra_data.dia_semana+" "+mostra_data.dia+","+" de "+mostra_data.mes+
                " de "+mostra_data.ano);
        timer1.start();//iniciar o processo
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_data = new javax.swing.JLabel();
        label_hora = new javax.swing.JLabel();
        botao_buscarapcliente = new javax.swing.JButton();
        botao_telacadcli = new javax.swing.JButton();
        botao_telacadprofinal = new javax.swing.JButton();
        botao_telacadmatprima = new javax.swing.JButton();
        botao_vendas = new javax.swing.JButton();
        botao_relatorios = new javax.swing.JButton();
        botao_cadas_login = new javax.swing.JButton();
        botao_sair2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema para controle de estoque");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/BackgroundTelaPrincipal.jpg"))); // NOI18N

        jLabel2.setText("Sistema desenvolvido por Victor Borges, Diogo Soares, Michele Silva, Italo Raniery.");

        label_data.setText("Data:");

        label_hora.setText("Hora:");

        botao_buscarapcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/usuarios.gif"))); // NOI18N
        botao_buscarapcliente.setText("Busca Rápida de Clientes");
        botao_buscarapcliente.setMaximumSize(new java.awt.Dimension(125, 41));
        botao_buscarapcliente.setMinimumSize(new java.awt.Dimension(125, 41));
        botao_buscarapcliente.setPreferredSize(new java.awt.Dimension(125, 41));
        botao_buscarapcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_buscarapclienteActionPerformed(evt);
            }
        });

        botao_telacadcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/usuarios.gif"))); // NOI18N
        botao_telacadcli.setText("Clientes");
        botao_telacadcli.setMaximumSize(new java.awt.Dimension(125, 41));
        botao_telacadcli.setMinimumSize(new java.awt.Dimension(125, 41));
        botao_telacadcli.setPreferredSize(new java.awt.Dimension(125, 41));
        botao_telacadcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_telacadcliActionPerformed(evt);
            }
        });

        botao_telacadprofinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/tintas.png"))); // NOI18N
        botao_telacadprofinal.setText("Produto Final");
        botao_telacadprofinal.setMaximumSize(new java.awt.Dimension(125, 41));
        botao_telacadprofinal.setMinimumSize(new java.awt.Dimension(125, 41));
        botao_telacadprofinal.setPreferredSize(new java.awt.Dimension(125, 41));
        botao_telacadprofinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_telacadprofinalActionPerformed(evt);
            }
        });

        botao_telacadmatprima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/cadastro_bairros.gif"))); // NOI18N
        botao_telacadmatprima.setText("Matéria Prima");
        botao_telacadmatprima.setAutoscrolls(true);
        botao_telacadmatprima.setMaximumSize(new java.awt.Dimension(125, 41));
        botao_telacadmatprima.setMinimumSize(new java.awt.Dimension(125, 41));
        botao_telacadmatprima.setPreferredSize(new java.awt.Dimension(125, 41));
        botao_telacadmatprima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_telacadmatprimaActionPerformed(evt);
            }
        });

        botao_vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/cifrao.png"))); // NOI18N
        botao_vendas.setText("Vendas");
        botao_vendas.setMaximumSize(new java.awt.Dimension(125, 41));
        botao_vendas.setMinimumSize(new java.awt.Dimension(125, 41));
        botao_vendas.setPreferredSize(new java.awt.Dimension(125, 41));
        botao_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_vendasActionPerformed(evt);
            }
        });

        botao_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/iconrelatorio.png"))); // NOI18N
        botao_relatorios.setText("Relatórios");
        botao_relatorios.setMaximumSize(new java.awt.Dimension(125, 41));
        botao_relatorios.setMinimumSize(new java.awt.Dimension(125, 41));
        botao_relatorios.setPreferredSize(new java.awt.Dimension(125, 41));
        botao_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_relatoriosActionPerformed(evt);
            }
        });

        botao_cadas_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Cadastrologin.png"))); // NOI18N
        botao_cadas_login.setText("Cadastro de usuários");
        botao_cadas_login.setMaximumSize(new java.awt.Dimension(125, 41));
        botao_cadas_login.setMinimumSize(new java.awt.Dimension(125, 41));
        botao_cadas_login.setPreferredSize(new java.awt.Dimension(125, 41));
        botao_cadas_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadas_loginActionPerformed(evt);
            }
        });

        botao_sair2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/sair.gif"))); // NOI18N
        botao_sair2.setText("Sair");
        botao_sair2.setMaximumSize(new java.awt.Dimension(125, 41));
        botao_sair2.setMinimumSize(new java.awt.Dimension(125, 41));
        botao_sair2.setPreferredSize(new java.awt.Dimension(125, 41));
        botao_sair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sair2ActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_data)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botao_telacadcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botao_telacadprofinal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botao_telacadmatprima, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botao_buscarapcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botao_vendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botao_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botao_cadas_login, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botao_sair2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_hora)
                        .addGap(48, 48, 48))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_telacadcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_telacadprofinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_telacadmatprima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao_vendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_buscarapcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_cadas_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_sair2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(label_hora))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1356, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
         mostra_data.le_hora();
        label_hora.setText("Hora atual:  "+mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void botao_buscarapclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_buscarapclienteActionPerformed
        try {
            new TelaPesqRapCliente().setVisible(true);//que quer abrir
        } catch (ConexaoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_botao_buscarapclienteActionPerformed

    private void botao_telacadmatprimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_telacadmatprimaActionPerformed
        try {
            new TelaCadMatPrima().setVisible(true);//que quer abrir
        } catch (ConexaoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }   
    // TODO add your handling code here:
    }//GEN-LAST:event_botao_telacadmatprimaActionPerformed

    private void botao_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_vendasActionPerformed
        try{
        TelaVendas tl = new TelaVendas();
       
        tl.setVisible(true);
         } catch (ConexaoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botao_vendasActionPerformed

    private void botao_telacadprofinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_telacadprofinalActionPerformed
        try {
            new TelaCadProdFinal().setVisible(true);//que quer abrir
        } catch (ConexaoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_telacadprofinalActionPerformed

    private void botao_telacadcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_telacadcliActionPerformed
        try {
            new TelaCadCliente().setVisible(true);//que quer abrir
        } catch (ConexaoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_telacadcliActionPerformed

    private void botao_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_relatoriosActionPerformed
       new TelaRelatorios().setVisible(true);//que quer abrir
 
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_relatoriosActionPerformed

    private void botao_cadas_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadas_loginActionPerformed
        try {
            new CadastroLogin().setVisible(true);
            // TODO add your handling code here:
        } catch (ConexaoException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botao_cadas_loginActionPerformed

    private void botao_sair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sair2ActionPerformed
        System.exit(0);        
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_sair2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_buscarapcliente;
    private javax.swing.JButton botao_cadas_login;
    private javax.swing.JButton botao_relatorios;
    private javax.swing.JButton botao_sair2;
    private javax.swing.JButton botao_telacadcli;
    private javax.swing.JButton botao_telacadmatprima;
    private javax.swing.JButton botao_telacadprofinal;
    private javax.swing.JButton botao_vendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_hora;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
