-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE PRODSAIDA (
CODPRODSAIDA VARCHAR(10) PRIMARY KEY,
LOGIN VARCHAR(10),
PRODUTO VARCHAR(40 ),
NCM INTEGER,
UNICOMERCIAL VARCHAR(11 ),
PRECO VARCHAR(8),
DESCRICAO Número(100),
QTD VARCHAR(8),
QTDMIN Número(4)
)

CREATE TABLE PRODENTRADA (
CODPRODENTRADA VARCHAR(10) PRIMARY KEY,
LOGIN VARCHAR(10),
PRODUTO VARCHAR(32 ),
NUMNF VARCHAR(10 ),
EMISSAO VARCHAR(10),
QTD VARCHAR(8 ),
PRECO VARCHAR(8 ),
UNICOMERCIAL VARCHAR(5 ),
ICMS VARCHAR(4),
DIF_ICMS VARCHAR(5 ),
PRECOFINAL VARCHAR(8 ),
IPI VARCHAR(4),
DESCRICAO VARCHAR(100),
QTDMIN Número(4)
)

CREATE TABLE FORNECEDOR (
CODFORMECEDOR  VARCHAR(10) PRIMARY KEY,
CNPJ VARCHAR(16 ),
NOMEFANT Número(4),
MUNICIPIO VARCHAR(32 ),
UF VARCHAR( 5),
LOGADOURO VARCHAR(32)
)

CREATE TABLE USUARIO (
LOGIN VARCHAR(10) PRIMARY KEY,
SENHA VARCHAR(12)
)

CREATE TABLE CLIENTE (
CODCLIENTE VARCHAR(10) PRIMARY KEY,
LOGIN VARCHAR(10),
NOME VARCHAR(52 ),
LOGADOURO VARCHAR(60 ),
NUMERO INTEGER,
BAIRRO VARCHAR(50),
CODMUNICIPIO INTEGER,
MUNICIPIO Número(33),
UF VARCHAR(2),
CODPAIS INTEGER,
PAIS VARCHAR(22),
FONE Número(16),
FONE2 VARCHAR(16),
EMAIL VARCHAR(50),
CPF VARCHAR(20 ),
DATA Número(10),
FOREIGN KEY(LOGIN) REFERENCES USUARIO (LOGIN)
)

CREATE TABLE COMPRA (
CODCOMPRA VARCHAR(10) PRIMARY KEY,
CODFORMECEDOR  VARCHAR(10),
CODPRODENTRADA VARCHAR(10),
DTCOMPRA VARCHAR(11 ),
PRECOCOMPRA VARCHAR(8),
FOREIGN KEY(CODFORMECEDOR ) REFERENCES FORNECEDOR (CODFORMECEDOR),
FOREIGN KEY(CODPRODENTRADA) REFERENCES PRODENTRADA (CODPRODENTRADA)
)

CREATE TABLE VENDA (
CODPRODSAIDA VARCHAR(10),
CODCLIENTE VARCHAR(10),
CODVENDA VARCHAR(10) PRIMARY KEY,
DTVENDA VARCHAR(11),
PRECOVEND VARCHAR(8),
FOREIGN KEY(CODPRODSAIDA) REFERENCES PRODSAIDA (CODPRODSAIDA),
FOREIGN KEY(CODCLIENTE) REFERENCES CLIENTE (CODCLIENTE)
)

ALTER TABLE PRODSAIDA ADD FOREIGN KEY(LOGIN) REFERENCES USUARIO (LOGIN)
ALTER TABLE PRODENTRADA ADD FOREIGN KEY(LOGIN) REFERENCES USUARIO (LOGIN)
